// train-model.js
const { NlpManager } = require('node-nlp');

// Create an NLP manager for English with NER enabled
const manager = new NlpManager({ languages: ['en'], forceNER: true });

// Add training examples for your intents

// complaint.add
manager.addDocument('en', 'I want to add a complaint', 'complaint.add');
manager.addDocument('en', 'Submit a complaint', 'complaint.add');
manager.addDocument('en', 'Add a new complaint', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint', 'complaint.add');
manager.addDocument('en', 'Can I submit a complaint?', 'complaint.add');
manager.addDocument('en', 'I\'d like to lodge a complaint', 'complaint.add');
manager.addDocument('en', 'I need to register a complaint', 'complaint.add');
manager.addDocument('en', 'Please add my complaint', 'complaint.add');
manager.addDocument('en', 'Help me file a complaint', 'complaint.add');
manager.addDocument('en', 'I wish to submit a new complaint', 'complaint.add');
manager.addDocument('en', 'I\'d like to report an issue', 'complaint.add');
manager.addDocument('en', 'Can you register a complaint for me?', 'complaint.add');
manager.addDocument('en', 'I need to raise a complaint', 'complaint.add');
manager.addDocument('en', 'I\'d like to submit a formal complaint', 'complaint.add');
manager.addDocument('en', 'Please register my complaint', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint', 'complaint.add');
manager.addDocument('en', 'I want to file a formal complaint', 'complaint.add');
manager.addDocument('en', 'I need to log a complaint', 'complaint.add');
manager.addDocument('en', 'I need to complain about something', 'complaint.add');
manager.addDocument('en', 'I have an issue to report', 'complaint.add');
manager.addDocument('en', 'I’d like to report a problem', 'complaint.add');
manager.addDocument('en', 'I want to make a report about an issue', 'complaint.add');
manager.addDocument('en', 'I have a grievance to submit', 'complaint.add');
manager.addDocument('en', 'I need to file a grievance', 'complaint.add');
manager.addDocument('en', 'Please add my issue to the system', 'complaint.add');
manager.addDocument('en', 'I want to report a technical problem', 'complaint.add');
manager.addDocument('en', 'There is something I need to complain about', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint regarding a product', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint about a service', 'complaint.add');
manager.addDocument('en', 'Please report my issue', 'complaint.add');
manager.addDocument('en', 'I want to make an official complaint', 'complaint.add');
manager.addDocument('en', 'Can you submit a complaint for me?', 'complaint.add');
manager.addDocument('en', 'I need to submit a formal issue', 'complaint.add');
manager.addDocument('en', 'Please log a complaint for me', 'complaint.add');
manager.addDocument('en', 'I’d like to submit a concern', 'complaint.add');
manager.addDocument('en', 'I want to report a concern', 'complaint.add');
manager.addDocument('en', 'I have an issue that needs to be addressed', 'complaint.add');
manager.addDocument('en', 'Can you log this complaint for me?', 'complaint.add');
manager.addDocument('en', 'I have a complaint I need to file', 'complaint.add');
manager.addDocument('en', 'Please file this complaint', 'complaint.add');
manager.addDocument('en', 'I want to make a formal complaint about this', 'complaint.add');
manager.addDocument('en', 'Please report my issue officially', 'complaint.add');
manager.addDocument('en', 'I’d like to file a complaint against someone', 'complaint.add');
manager.addDocument('en', 'I want to report an incident', 'complaint.add');
manager.addDocument('en', 'I want to log a complaint about my experience', 'complaint.add');
manager.addDocument('en', 'I need to add a complaint about customer service', 'complaint.add');
manager.addDocument('en', 'I have a problem I need to complain about', 'complaint.add');
manager.addDocument('en', 'I want to report a problem with my order', 'complaint.add');
manager.addDocument('en', 'Please add this issue to the complaints system', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint about your product', 'complaint.add');
manager.addDocument('en', 'I need to report a service failure', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint regarding delivery', 'complaint.add');
manager.addDocument('en', 'Please add my complaint about the staff', 'complaint.add');
manager.addDocument('en', 'I have a complaint about the quality of service', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint about a charge', 'complaint.add');
manager.addDocument('en', 'Please register a complaint about the website', 'complaint.add');
manager.addDocument('en', 'I want to report a broken product', 'complaint.add');
manager.addDocument('en', 'I need to report a broken item I received', 'complaint.add');
manager.addDocument('en', 'I want to complain about faulty service', 'complaint.add');
manager.addDocument('en', 'Please file a complaint for me', 'complaint.add');
manager.addDocument('en', 'I want to submit a formal grievance', 'complaint.add');
manager.addDocument('en', 'Please make a complaint on my behalf', 'complaint.add');
manager.addDocument('en', 'I have an issue I need addressed', 'complaint.add');
manager.addDocument('en', 'Please help me register a complaint', 'complaint.add');
manager.addDocument('en', 'I’d like to make a formal complaint about the delay', 'complaint.add');
manager.addDocument('en', 'Please report the issue with the delivery', 'complaint.add');
manager.addDocument('en', 'Can you help me file a complaint?', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint about your service', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint about a malfunction', 'complaint.add');
manager.addDocument('en', 'Please submit a complaint for me', 'complaint.add');
manager.addDocument('en', 'I have a complaint to report', 'complaint.add');
manager.addDocument('en', 'I want to submit a complaint regarding the quality', 'complaint.add');
manager.addDocument('en', 'Please file a complaint on my behalf', 'complaint.add');
manager.addDocument('en', 'I need to report a bad experience', 'complaint.add');

// complaint.view
manager.addDocument('en', 'I want to view my complaint', 'complaint.view');
manager.addDocument('en', 'Show me my complaints', 'complaint.view');
manager.addDocument('en', 'View complaint number 123', 'complaint.view');
manager.addDocument('en', 'Show me my complaints list', 'complaint.view');
manager.addDocument('en', 'I want to see my complaint', 'complaint.view');
manager.addDocument('en', 'Can you display my complaint?', 'complaint.view');
manager.addDocument('en', 'I would like to check my complaints', 'complaint.view');
manager.addDocument('en', 'Let me view my complaint status', 'complaint.view');
manager.addDocument('en', 'Give me the details of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to look at complaint number 456', 'complaint.view');
manager.addDocument('en', 'Can you show complaint 789?', 'complaint.view');
manager.addDocument('en', 'Please show the complaint I submitted', 'complaint.view');
manager.addDocument('en', 'What is the status of my complaint?', 'complaint.view');
manager.addDocument('en', 'Show me the status of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to check the status of my complaint', 'complaint.view');
manager.addDocument('en', 'Please show my complaint status', 'complaint.view');
manager.addDocument('en', 'Can you give me the status of my complaint?', 'complaint.view');
manager.addDocument('en', 'I want to know the status of complaint number 123', 'complaint.view');
manager.addDocument('en', 'Let me check my complaint', 'complaint.view');
manager.addDocument('en', 'What is the update on my complaint?', 'complaint.view');
manager.addDocument('en', 'Can I check the progress of my complaint?', 'complaint.view');
manager.addDocument('en', 'I need to view my complaint details', 'complaint.view');
manager.addDocument('en', 'Please show me the complaint I filed', 'complaint.view');
manager.addDocument('en', 'I want to review my complaint', 'complaint.view');
manager.addDocument('en', 'Can you display the details of my complaint?', 'complaint.view');
manager.addDocument('en', 'Give me a summary of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to know more about my complaint', 'complaint.view');
manager.addDocument('en', 'Can you provide an update on my complaint?', 'complaint.view');
manager.addDocument('en', 'Let me see the complaint status', 'complaint.view');
manager.addDocument('en', 'Show me the complaint details', 'complaint.view');
manager.addDocument('en', 'I would like to know the status of my complaint', 'complaint.view');
manager.addDocument('en', 'What is the status of complaint number 456?', 'complaint.view');
manager.addDocument('en', 'I want to know what happened to my complaint', 'complaint.view');
manager.addDocument('en', 'Please tell me the current status of my complaint', 'complaint.view');

// general.cancel
manager.addDocument('en', 'Cancel', 'general.cancel');
manager.addDocument('en', 'Exit', 'general.cancel');
manager.addDocument('en', 'Cancel the action', 'general.cancel');
manager.addDocument('en', 'Forget about it', 'general.cancel');
manager.addDocument('en', 'I don\'t want to proceed', 'general.cancel');
manager.addDocument('en', 'Stop the process', 'general.cancel');
manager.addDocument('en', 'Abort the operation', 'general.cancel');
manager.addDocument('en', 'Never mind', 'general.cancel');
manager.addDocument('en', 'I changed my mind', 'general.cancel');
manager.addDocument('en', 'Please cancel it', 'general.cancel');
manager.addDocument('en', 'Cancel this request', 'general.cancel');
manager.addDocument('en', 'Exit without submitting', 'general.cancel');
manager.addDocument('en', 'Forget this request', 'general.cancel');
manager.addDocument('en', 'Cancel the operation', 'general.cancel');
manager.addDocument('en', 'Stop everything', 'general.cancel');
manager.addDocument('en', 'Abort the task', 'general.cancel');
manager.addDocument('en', 'I no longer want to proceed', 'general.cancel');
manager.addDocument('en', 'Forget about the complaint', 'general.cancel');
manager.addDocument('en', 'Stop the process for me', 'general.cancel');
manager.addDocument('en', 'Cancel and exit', 'general.cancel');
manager.addDocument('en', 'End this now', 'general.cancel');
manager.addDocument('en', 'I want to stop this', 'general.cancel');
manager.addDocument('en', 'Don\'t proceed with the action', 'general.cancel');
manager.addDocument('en', 'Exit without confirming', 'general.cancel');
manager.addDocument('en', 'Cancel the entire process', 'general.cancel');
manager.addDocument('en', 'I want to exit', 'general.cancel');
manager.addDocument('en', 'Cancel the request I made', 'general.cancel');
manager.addDocument('en', 'I don\'t want to submit it anymore', 'general.cancel');
manager.addDocument('en', 'Forget the action I took', 'general.cancel');
manager.addDocument('en', 'Stop everything now', 'general.cancel');
manager.addDocument('en', 'Cancel this step', 'general.cancel');
manager.addDocument('en', 'Cancel my request', 'general.cancel');
manager.addDocument('en', 'Exit the process', 'general.cancel');
manager.addDocument('en', 'I want to cancel this', 'general.cancel');
manager.addDocument('en', 'I do not want to continue', 'general.cancel');
manager.addDocument('en', 'Cancel and stop', 'general.cancel');
manager.addDocument('en', 'Exit and cancel the process', 'general.cancel');
manager.addDocument('en', 'Forget everything', 'general.cancel');
manager.addDocument('en', 'End this process', 'general.cancel');
manager.addDocument('en', 'Please cancel everything', 'general.cancel');
manager.addDocument('en', 'Exit immediately', 'general.cancel');
manager.addDocument('en', 'Please stop this now', 'general.cancel');
manager.addDocument('en', 'I changed my decision', 'general.cancel');
manager.addDocument('en', 'Abort everything', 'general.cancel');
manager.addDocument('en', 'Cancel my previous action', 'general.cancel');
manager.addDocument('en', 'Don\'t proceed with this request', 'general.cancel');
manager.addDocument('en', 'End this operation', 'general.cancel');
manager.addDocument('en', 'Cancel and exit now', 'general.cancel');
manager.addDocument('en', 'Exit the current process', 'general.cancel');
manager.addDocument('en', 'Stop right now', 'general.cancel');
manager.addDocument('en', 'Cancel without submitting', 'general.cancel');

// bot.details examples
manager.addDocument('en', 'Who made you?', 'bot.details');
manager.addDocument('en', 'Who is your creator?', 'bot.details');
manager.addDocument('en', 'Tell me about yourself', 'bot.details');
manager.addDocument('en', 'Who developed you?', 'bot.details');

// uor.info examples
manager.addDocument('en', 'Tell me about University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Give me information on UoR', 'uor.info');
manager.addDocument('en', 'University of Ruhuna details', 'uor.info');
manager.addDocument('en', 'What is the University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'Tell me more about UoR', 'uor.info');
manager.addDocument('en', 'Can you describe the University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'Give me some facts about UoR', 'uor.info');
manager.addDocument('en', 'I want to know about University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Tell me something about UoR', 'uor.info');
manager.addDocument('en', 'Share details about the University of Ruhuna', 'uor.info');
manager.addDocument('en', 'What is UoR known for?', 'uor.info');
manager.addDocument('en', 'UoR information', 'uor.info');
manager.addDocument('en', 'Explain University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Basic info on UoR', 'uor.info');
manager.addDocument('en', 'UoR profile', 'uor.info');
manager.addDocument('en', 'University of Ruhuna introduction', 'uor.info');
manager.addDocument('en', 'Brief on UoR', 'uor.info');
manager.addDocument('en', 'History of University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Is University of Ruhuna a good university?', 'uor.info');
manager.addDocument('en', 'Where is the University of Ruhuna located?', 'uor.info');
manager.addDocument('en', 'Tell me about UoR', 'uor.info');
manager.addDocument('en', 'What can you tell me about University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'University of Ruhuna overview', 'uor.info');
manager.addDocument('en', 'University of Ruhuna quick facts', 'uor.info');
manager.addDocument('en', 'What is special about UoR?', 'uor.info');
manager.addDocument('en', 'Facts about UoR', 'uor.info');
manager.addDocument('en', 'How is University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'About UoR', 'uor.info');
manager.addDocument('en', 'Give me a summary of University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Overview of UoR', 'uor.info');
manager.addDocument('en', 'What do you know about UoR?', 'uor.info');
manager.addDocument('en', 'What is the reputation of UoR?', 'uor.info');
manager.addDocument('en', 'Tell me about the university in Matara', 'uor.info');
manager.addDocument('en', 'University of Ruhuna campus info', 'uor.info');
manager.addDocument('en', 'How old is University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'What programs does UoR offer?', 'uor.info');
manager.addDocument('en', 'Explain about UoR', 'uor.info');
manager.addDocument('en', 'Information about UoR please', 'uor.info');
manager.addDocument('en', 'University of Ruhuna background', 'uor.info');
manager.addDocument('en', 'Give me data on University of Ruhuna', 'uor.info');
manager.addDocument('en', 'UoR description', 'uor.info');
manager.addDocument('en', 'Share some info on UoR', 'uor.info');
manager.addDocument('en', 'What does UoR stand for?', 'uor.info');
manager.addDocument('en', 'Location and history of University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Why choose UoR?', 'uor.info');
manager.addDocument('en', 'Key facts about University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Does UoR have engineering?', 'uor.info');
manager.addDocument('en', 'Top courses at University of Ruhuna', 'uor.info');
manager.addDocument('en', 'University of Ruhuna academics', 'uor.info');
manager.addDocument('en', 'Research at UoR', 'uor.info');
manager.addDocument('en', 'Can you tell me about UoR?', 'uor.info');
manager.addDocument('en', 'What’s interesting about University of Ruhuna?', 'uor.info');
manager.addDocument('en', 'Tell me about faculties at UoR', 'uor.info');
manager.addDocument('en', 'What is UoR famous for?', 'uor.info');
manager.addDocument('en', 'University of Ruhuna courses', 'uor.info');
manager.addDocument('en', 'Give me full info on UoR', 'uor.info');
manager.addDocument('en', 'University of Ruhuna ranking', 'uor.info');
manager.addDocument('en', 'Student life at UoR', 'uor.info');
manager.addDocument('en', 'UoR achievements', 'uor.info');
manager.addDocument('en', 'Notable alumni of University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Does UoR have a good engineering faculty?', 'uor.info');
manager.addDocument('en', 'Give details on University of Ruhuna', 'uor.info');
manager.addDocument('en', 'What degrees does UoR provide?', 'uor.info');
manager.addDocument('en', 'Departments in University of Ruhuna', 'uor.info');
manager.addDocument('en', 'All about University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Everything about UoR', 'uor.info');
manager.addDocument('en', 'Give me UoR facts', 'uor.info');
manager.addDocument('en', 'Tell me UoR highlights', 'uor.info');
manager.addDocument('en', 'Info on University of Ruhuna please', 'uor.info');
manager.addDocument('en', 'Quick guide to UoR', 'uor.info');
manager.addDocument('en', 'Introduction to University of Ruhuna', 'uor.info');
manager.addDocument('en', 'UoR info request', 'uor.info');
manager.addDocument('en', 'Give me a briefing on UoR', 'uor.info');
manager.addDocument('en', 'Explore University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Tell me about the Matara university', 'uor.info');
manager.addDocument('en', 'University of Ruhuna identity', 'uor.info');
manager.addDocument('en', 'Info about the Ruhuna campus', 'uor.info');
manager.addDocument('en', 'Help me learn about UoR', 'uor.info');
manager.addDocument('en', 'University of Ruhuna key info', 'uor.info');
manager.addDocument('en', 'UoR university information', 'uor.info');
manager.addDocument('en', 'University of Ruhuna factsheet', 'uor.info');
manager.addDocument('en', 'I need information about UoR', 'uor.info');
manager.addDocument('en', 'UoR main facts', 'uor.info');
manager.addDocument('en', 'Give me an idea of University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Tell me about the faculties of UoR', 'uor.info');
manager.addDocument('en', 'Insight on University of Ruhuna', 'uor.info');
manager.addDocument('en', 'Is University of Ruhuna in Sri Lanka?', 'uor.info');
manager.addDocument('en', 'Name some departments at UoR', 'uor.info');
manager.addDocument('en', 'Which courses are at UoR?', 'uor.info');
manager.addDocument('en', 'Is UoR a public university?', 'uor.info');
manager.addDocument('en', 'Tell me about UoR academics', 'uor.info');
manager.addDocument('en', 'UoR student community', 'uor.info');
manager.addDocument('en', 'University of Ruhuna research fields', 'uor.info');
manager.addDocument('en', 'Study opportunities at UoR', 'uor.info');
manager.addDocument('en', 'General info on UoR', 'uor.info');
manager.addDocument('en', 'Give me some facts and history of UoR', 'uor.info');
manager.addDocument('en', 'Can you show me University of Ruhuna details?', 'uor.info');
manager.addDocument('en', 'University of Ruhuna education system', 'uor.info');
manager.addDocument('en', 'Is UoR a good place to study?', 'uor.info');
manager.addDocument('en', 'Background info on UoR', 'uor.info');
manager.addDocument('en', 'UoR university overview', 'uor.info');

// efac.info examples
manager.addDocument('en', 'Tell me about Efac', 'efac.info');
manager.addDocument('en', 'Tell me about Efac', 'efac.info');
manager.addDocument('en', 'What is Efac?', 'efac.info');
manager.addDocument('en', 'Give me information about Efac', 'efac.info');
manager.addDocument('en', 'Details about the Faculty of Engineering, Ruhuna', 'efac.info');
manager.addDocument('en', 'Tell me about the engineering faculty of UoR', 'efac.info');
manager.addDocument('en', 'Information on Efac please', 'efac.info');
manager.addDocument('en', 'What does Efac stand for?', 'efac.info');
manager.addDocument('en', 'Explain Efac', 'efac.info');
manager.addDocument('en', 'Give me details on Ruhuna engineering faculty', 'efac.info');
manager.addDocument('en', 'Efac quick facts', 'efac.info');
manager.addDocument('en', 'I want to know about Efac', 'efac.info');
manager.addDocument('en', 'What is special about the Faculty of Engineering at Ruhuna?', 'efac.info');
manager.addDocument('en', 'Is Efac part of UoR?', 'efac.info');
manager.addDocument('en', 'Give me a brief about Efac', 'efac.info');
manager.addDocument('en', 'Engineering at UoR details', 'efac.info');
manager.addDocument('en', 'Tell me something about Efac', 'efac.info');
manager.addDocument('en', 'Can you explain Efac to me?', 'efac.info');
manager.addDocument('en', 'What can you tell me about Efac?', 'efac.info');
manager.addDocument('en', 'Share info about Efac', 'efac.info');
manager.addDocument('en', 'Efac - Faculty of Engineering info', 'efac.info');
manager.addDocument('en', 'What does the Faculty of Engineering at UoR offer?', 'efac.info');
manager.addDocument('en', 'All about Efac', 'efac.info');
manager.addDocument('en', 'Everything about Efac', 'efac.info');
manager.addDocument('en', 'Engineering faculty of UoR overview', 'efac.info');
manager.addDocument('en', 'What degrees does Efac provide?', 'efac.info');
manager.addDocument('en', 'Tell me about Ruhuna Engineering', 'efac.info');
manager.addDocument('en', 'Information about Efac', 'efac.info');
manager.addDocument('en', 'Can you tell me about Efac?', 'efac.info');
manager.addDocument('en', 'Efac programs and departments', 'efac.info');
manager.addDocument('en', 'Ruhuna engineering faculty description', 'efac.info');
manager.addDocument('en', 'What’s taught at Efac?', 'efac.info');
manager.addDocument('en', 'Departments at Efac', 'efac.info');
manager.addDocument('en', 'Courses at Efac', 'efac.info');
manager.addDocument('en', 'Overview of Efac', 'efac.info');
manager.addDocument('en', 'Share details about Efac', 'efac.info');
manager.addDocument('en', 'Give me insights into Efac', 'efac.info');
manager.addDocument('en', 'History of the Ruhuna engineering faculty', 'efac.info');
manager.addDocument('en', 'When was Efac started?', 'efac.info');
manager.addDocument('en', 'What is Efac known for?', 'efac.info');
manager.addDocument('en', 'How many departments are there in Efac?', 'efac.info');
manager.addDocument('en', 'Engineering education at UoR', 'efac.info');
manager.addDocument('en', 'Engineering in Ruhuna', 'efac.info');
manager.addDocument('en', 'Academic information about Efac', 'efac.info');
manager.addDocument('en', 'Tell me about engineering at Ruhuna', 'efac.info');
manager.addDocument('en', 'Efac course structure', 'efac.info');
manager.addDocument('en', 'What engineering streams are available in Efac?', 'efac.info');
manager.addDocument('en', 'Efac departments list', 'efac.info');
manager.addDocument('en', 'Engineering degrees at Ruhuna', 'efac.info');
manager.addDocument('en', 'Details about Efac courses', 'efac.info');
manager.addDocument('en', 'Student life at Efac', 'efac.info');
manager.addDocument('en', 'Faculty life in Efac', 'efac.info');
manager.addDocument('en', 'Ruhuna Efac facilities', 'efac.info');
manager.addDocument('en', 'Tell me about the students in Efac', 'efac.info');
manager.addDocument('en', 'Which engineering courses are available at UoR?', 'efac.info');
manager.addDocument('en', 'Give me academic info about Efac', 'efac.info');
manager.addDocument('en', 'Explain engineering faculty at Ruhuna', 'efac.info');
manager.addDocument('en', 'Is Efac a good engineering faculty?', 'efac.info');
manager.addDocument('en', 'Why choose Efac?', 'efac.info');
manager.addDocument('en', 'Facts about Efac', 'efac.info');
manager.addDocument('en', 'Tell me more about Efac at Ruhuna', 'efac.info');
manager.addDocument('en', 'Who can apply to Efac?', 'efac.info');
manager.addDocument('en', 'What are the qualifications for Efac?', 'efac.info');
manager.addDocument('en', 'Engineering at Matara UoR', 'efac.info');
manager.addDocument('en', 'Engineering campus of University of Ruhuna', 'efac.info');
manager.addDocument('en', 'UoR Faculty of Engineering', 'efac.info');
manager.addDocument('en', 'Tell me the full name of Efac', 'efac.info');
manager.addDocument('en', 'Engineering faculty info', 'efac.info');
manager.addDocument('en', 'UoR Efac information', 'efac.info');
manager.addDocument('en', 'Efac description', 'efac.info');
manager.addDocument('en', 'Information about Ruhuna Efac', 'efac.info');
manager.addDocument('en', 'How is the Faculty of Engineering at UoR?', 'efac.info');
manager.addDocument('en', 'Faculty of Engineering overview Ruhuna', 'efac.info');
manager.addDocument('en', 'Tell me about UoR’s Faculty of Engineering', 'efac.info');
manager.addDocument('en', 'Give me facts about Efac', 'efac.info');
manager.addDocument('en', 'Details about Faculty of Engineering Ruhuna', 'efac.info');
manager.addDocument('en', 'Efac educational programs', 'efac.info');
manager.addDocument('en', 'How many faculties are in Ruhuna?', 'efac.info');
manager.addDocument('en', 'Efac faculty members', 'efac.info');
manager.addDocument('en', 'Ruhuna engineering info', 'efac.info');
manager.addDocument('en', 'Let’s talk about Efac', 'efac.info');
manager.addDocument('en', 'Can I learn about Efac?', 'efac.info');
manager.addDocument('en', 'Academic units in Efac', 'efac.info');
manager.addDocument('en', 'Does Efac offer Computer Engineering?', 'efac.info');
manager.addDocument('en', 'Tell me about the Efac campus', 'efac.info');
manager.addDocument('en', 'Is Efac in Galle or Matara?', 'efac.info');
manager.addDocument('en', 'How many years is Efac degree?', 'efac.info');
manager.addDocument('en', 'Departments under Efac', 'efac.info');
manager.addDocument('en', 'Who are the deans of Efac?', 'efac.info');
manager.addDocument('en', 'Dean of Efac', 'efac.info');
manager.addDocument('en', 'Leadership at Efac', 'efac.info');
manager.addDocument('en', 'Tell me about student projects in Efac', 'efac.info');
manager.addDocument('en', 'Are there clubs in Efac?', 'efac.info');
manager.addDocument('en', 'Efac extracurriculars', 'efac.info');
manager.addDocument('en', 'Give me full information on Efac', 'efac.info');
manager.addDocument('en', 'Tell me what Efac stands for in UoR', 'efac.info');
manager.addDocument('en', 'Engineering undergraduates at Ruhuna', 'efac.info');
manager.addDocument('en', 'Tell me about the engineering faculty', 'efac.info');

// scorpionx.about examples
manager.addDocument('en', 'Tell me about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Who is Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'About the maker of bot', 'scorpionx.about');
manager.addDocument('en', 'Who built this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Who created this bot?', 'scorpionx.about');
manager.addDocument('en', 'What is Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Give me info about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Tell me who Scorpion X is', 'scorpionx.about');
manager.addDocument('en', 'Who is behind this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Who made you?', 'scorpionx.about');
manager.addDocument('en', 'Who developed this assistant?', 'scorpionx.about');
manager.addDocument('en', 'Who’s your creator?', 'scorpionx.about');
manager.addDocument('en', 'Tell me the person behind you', 'scorpionx.about');
manager.addDocument('en', 'Introduce Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Details about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Creator of this chatbot', 'scorpionx.about');
manager.addDocument('en', 'Let me know about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'What can you tell me about Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'I want to know who made you', 'scorpionx.about');
manager.addDocument('en', 'Who designed this AI?', 'scorpionx.about');
manager.addDocument('en', 'Who’s the developer of this bot?', 'scorpionx.about');
manager.addDocument('en', 'Share about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Reveal the bot creator', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X identity', 'scorpionx.about');
manager.addDocument('en', 'Person behind Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Who is the mind behind this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Give me background on Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Was this bot made by Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Who made this?', 'scorpionx.about');
manager.addDocument('en', 'What’s the story of Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Do you know who built you?', 'scorpionx.about');
manager.addDocument('en', 'About the developer Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Who programmed this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Tell me more about your creator', 'scorpionx.about');
manager.addDocument('en', 'Talk about the person who made you', 'scorpionx.about');
manager.addDocument('en', 'Say something about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X profile', 'scorpionx.about');
manager.addDocument('en', 'The mastermind behind this bot', 'scorpionx.about');
manager.addDocument('en', 'Creator info of this AI', 'scorpionx.about');
manager.addDocument('en', 'Bot creator details', 'scorpionx.about');
manager.addDocument('en', 'Who is your developer?', 'scorpionx.about');
manager.addDocument('en', 'Developer name of this bot?', 'scorpionx.about');
manager.addDocument('en', 'Information about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Full name of Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Background of Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Where is Scorpion X from?', 'scorpionx.about');
manager.addDocument('en', 'Where did Scorpion X learn to code?', 'scorpionx.about');
manager.addDocument('en', 'Is Scorpion X your developer?', 'scorpionx.about');
manager.addDocument('en', 'Is Scorpion X a real person?', 'scorpionx.about');
manager.addDocument('en', 'More details about the bot maker', 'scorpionx.about');
manager.addDocument('en', 'Who is the genius behind you?', 'scorpionx.about');
manager.addDocument('en', 'Who worked on this bot?', 'scorpionx.about');
manager.addDocument('en', 'Was Scorpion X a student?', 'scorpionx.about');
manager.addDocument('en', 'How was this bot created?', 'scorpionx.about');
manager.addDocument('en', 'Who handled this AI’s creation?', 'scorpionx.about');
manager.addDocument('en', 'Creator of this AI system', 'scorpionx.about');
manager.addDocument('en', 'Who gave you life?', 'scorpionx.about');
manager.addDocument('en', 'Tell me who Scorpion X really is', 'scorpionx.about');
manager.addDocument('en', 'Do you have a developer?', 'scorpionx.about');
manager.addDocument('en', 'Your bot maker?', 'scorpionx.about');
manager.addDocument('en', 'Tell me something about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Introduce your creator', 'scorpionx.about');
manager.addDocument('en', 'Who launched you?', 'scorpionx.about');
manager.addDocument('en', 'Is Scorpion X your programmer?', 'scorpionx.about');
manager.addDocument('en', 'Who’s the bot author?', 'scorpionx.about');
manager.addDocument('en', 'I want to learn about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Talk to me about your maker', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X full details', 'scorpionx.about');
manager.addDocument('en', 'How do I learn more about Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Was this bot coded by Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Bot maker introduction', 'scorpionx.about');
manager.addDocument('en', 'Your creator’s identity?', 'scorpionx.about');
manager.addDocument('en', 'Who trained this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Who wrote the code for you?', 'scorpionx.about');
manager.addDocument('en', 'Info about your developer', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X info summary', 'scorpionx.about');
manager.addDocument('en', 'Profile of your creator', 'scorpionx.about');
manager.addDocument('en', 'Your origins and creator', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X, your creator, tell me more', 'scorpionx.about');
manager.addDocument('en', 'Do you know your developer?', 'scorpionx.about');
manager.addDocument('en', 'About the brain behind this bot', 'scorpionx.about');
manager.addDocument('en', 'This bot was made by?', 'scorpionx.about');
manager.addDocument('en', 'Who set up this bot?', 'scorpionx.about');
manager.addDocument('en', 'Can you tell who made you?', 'scorpionx.about');
manager.addDocument('en', 'Bot’s creator info', 'scorpionx.about');
manager.addDocument('en', 'Reveal developer identity', 'scorpionx.about');
manager.addDocument('en', 'Who is Scorpion X in real life?', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X – who’s that?', 'scorpionx.about');
manager.addDocument('en', 'Tell about Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Enlighten me on Scorpion X', 'scorpionx.about');
manager.addDocument('en', 'Can I know about Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Who’s your mastermind?', 'scorpionx.about');
manager.addDocument('en', 'Introduce the one who made this', 'scorpionx.about');
manager.addDocument('en', 'Who is responsible for this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Scorpion X – developer of this chatbot?', 'scorpionx.about');
manager.addDocument('en', 'Was this made by someone named Scorpion X?', 'scorpionx.about');
manager.addDocument('en', 'Who’s the builder of this system?', 'scorpionx.about');
manager.addDocument('en', 'Who’s the one who created you?', 'scorpionx.about');

// Train and save the model
(async () => {
  await manager.train();
  manager.save();
  console.log('Model trained and saved');
})();
