// train-model.js
const { NlpManager } = require('node-nlp');

// Create an NLP manager for English with NER enabled
const manager = new NlpManager({ languages: ['en'], forceNER: true });

// Add training examples for your intents
// complaint.add
manager.addDocument('en', 'I want to add a complaint', 'complaint.add');
manager.addDocument('en', 'Submit a complaint', 'complaint.add');
manager.addDocument('en', 'Add a new complaint', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint', 'complaint.add');
manager.addDocument('en', 'Can I submit a complaint?', 'complaint.add');
manager.addDocument('en', 'I\'d like to lodge a complaint', 'complaint.add');
manager.addDocument('en', 'I need to register a complaint', 'complaint.add');
manager.addDocument('en', 'Please add my complaint', 'complaint.add');
manager.addDocument('en', 'Help me file a complaint', 'complaint.add');
manager.addDocument('en', 'I wish to submit a new complaint', 'complaint.add');
manager.addDocument('en', 'I\'d like to report an issue', 'complaint.add');
manager.addDocument('en', 'Can you register a complaint for me?', 'complaint.add');
manager.addDocument('en', 'I need to raise a complaint', 'complaint.add');
manager.addDocument('en', 'I\'d like to submit a formal complaint', 'complaint.add');
manager.addDocument('en', 'Please register my complaint', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint', 'complaint.add');
manager.addDocument('en', 'I want to file a formal complaint', 'complaint.add');
manager.addDocument('en', 'I need to log a complaint', 'complaint.add');
manager.addDocument('en', 'I need to complain about something', 'complaint.add');
manager.addDocument('en', 'I have an issue to report', 'complaint.add');
manager.addDocument('en', 'I’d like to report a problem', 'complaint.add');
manager.addDocument('en', 'I want to make a report about an issue', 'complaint.add');
manager.addDocument('en', 'I have a grievance to submit', 'complaint.add');
manager.addDocument('en', 'I need to file a grievance', 'complaint.add');
manager.addDocument('en', 'Please add my issue to the system', 'complaint.add');
manager.addDocument('en', 'I want to report a technical problem', 'complaint.add');
manager.addDocument('en', 'There is something I need to complain about', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint regarding a product', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint about a service', 'complaint.add');
manager.addDocument('en', 'Please report my issue', 'complaint.add');
manager.addDocument('en', 'I want to make an official complaint', 'complaint.add');
manager.addDocument('en', 'Can you submit a complaint for me?', 'complaint.add');
manager.addDocument('en', 'I need to submit a formal issue', 'complaint.add');
manager.addDocument('en', 'Please log a complaint for me', 'complaint.add');
manager.addDocument('en', 'I’d like to submit a concern', 'complaint.add');
manager.addDocument('en', 'I want to report a concern', 'complaint.add');
manager.addDocument('en', 'I have an issue that needs to be addressed', 'complaint.add');
manager.addDocument('en', 'Can you log this complaint for me?', 'complaint.add');
manager.addDocument('en', 'I have a complaint I need to file', 'complaint.add');
manager.addDocument('en', 'Please file this complaint', 'complaint.add');
manager.addDocument('en', 'I want to make a formal complaint about this', 'complaint.add');
manager.addDocument('en', 'Please report my issue officially', 'complaint.add');
manager.addDocument('en', 'I’d like to file a complaint against someone', 'complaint.add');
manager.addDocument('en', 'I want to report an incident', 'complaint.add');
manager.addDocument('en', 'I want to log a complaint about my experience', 'complaint.add');
manager.addDocument('en', 'I need to add a complaint about customer service', 'complaint.add');
manager.addDocument('en', 'I have a problem I need to complain about', 'complaint.add');
manager.addDocument('en', 'I want to report a problem with my order', 'complaint.add');
manager.addDocument('en', 'Please add this issue to the complaints system', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint about your product', 'complaint.add');
manager.addDocument('en', 'I need to report a service failure', 'complaint.add');
manager.addDocument('en', 'I want to file a complaint regarding delivery', 'complaint.add');
manager.addDocument('en', 'Please add my complaint about the staff', 'complaint.add');
manager.addDocument('en', 'I have a complaint about the quality of service', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint about a charge', 'complaint.add');
manager.addDocument('en', 'Please register a complaint about the website', 'complaint.add');
manager.addDocument('en', 'I want to report a broken product', 'complaint.add');
manager.addDocument('en', 'I need to report a broken item I received', 'complaint.add');
manager.addDocument('en', 'I want to complain about faulty service', 'complaint.add');
manager.addDocument('en', 'Please file a complaint for me', 'complaint.add');
manager.addDocument('en', 'I want to submit a formal grievance', 'complaint.add');
manager.addDocument('en', 'Please make a complaint on my behalf', 'complaint.add');
manager.addDocument('en', 'I have an issue I need addressed', 'complaint.add');
manager.addDocument('en', 'Please help me register a complaint', 'complaint.add');
manager.addDocument('en', 'I’d like to make a formal complaint about the delay', 'complaint.add');
manager.addDocument('en', 'Please report the issue with the delivery', 'complaint.add');
manager.addDocument('en', 'Can you help me file a complaint?', 'complaint.add');
manager.addDocument('en', 'I want to make a complaint about your service', 'complaint.add');
manager.addDocument('en', 'I need to file a complaint about a malfunction', 'complaint.add');
manager.addDocument('en', 'Please submit a complaint for me', 'complaint.add');
manager.addDocument('en', 'I have a complaint to report', 'complaint.add');
manager.addDocument('en', 'I want to submit a complaint regarding the quality', 'complaint.add');
manager.addDocument('en', 'Please file a complaint on my behalf', 'complaint.add');
manager.addDocument('en', 'I need to report a bad experience', 'complaint.add');

// complaint.view
manager.addDocument('en', 'I want to view my complaint', 'complaint.view');
manager.addDocument('en', 'Show me my complaints', 'complaint.view');
manager.addDocument('en', 'View complaint number 123', 'complaint.view');
manager.addDocument('en', 'Show me my complaints list', 'complaint.view');
manager.addDocument('en', 'I want to see my complaint', 'complaint.view');
manager.addDocument('en', 'Can you display my complaint?', 'complaint.view');
manager.addDocument('en', 'I would like to check my complaints', 'complaint.view');
manager.addDocument('en', 'Let me view my complaint status', 'complaint.view');
manager.addDocument('en', 'Give me the details of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to look at complaint number 456', 'complaint.view');
manager.addDocument('en', 'Can you show complaint 789?', 'complaint.view');
manager.addDocument('en', 'Please show the complaint I submitted', 'complaint.view');
manager.addDocument('en', 'What is the status of my complaint?', 'complaint.view');
manager.addDocument('en', 'Show me the status of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to check the status of my complaint', 'complaint.view');
manager.addDocument('en', 'Please show my complaint status', 'complaint.view');
manager.addDocument('en', 'Can you give me the status of my complaint?', 'complaint.view');
manager.addDocument('en', 'I want to know the status of complaint number 123', 'complaint.view');
manager.addDocument('en', 'Let me check my complaint', 'complaint.view');
manager.addDocument('en', 'What is the update on my complaint?', 'complaint.view');
manager.addDocument('en', 'Can I check the progress of my complaint?', 'complaint.view');
manager.addDocument('en', 'I need to view my complaint details', 'complaint.view');
manager.addDocument('en', 'Please show me the complaint I filed', 'complaint.view');
manager.addDocument('en', 'I want to review my complaint', 'complaint.view');
manager.addDocument('en', 'Can you display the details of my complaint?', 'complaint.view');
manager.addDocument('en', 'Give me a summary of my complaint', 'complaint.view');
manager.addDocument('en', 'I want to know more about my complaint', 'complaint.view');
manager.addDocument('en', 'Can you provide an update on my complaint?', 'complaint.view');
manager.addDocument('en', 'Let me see the complaint status', 'complaint.view');
manager.addDocument('en', 'Show me the complaint details', 'complaint.view');
manager.addDocument('en', 'I would like to know the status of my complaint', 'complaint.view');
manager.addDocument('en', 'What is the status of complaint number 456?', 'complaint.view');
manager.addDocument('en', 'I want to know what happened to my complaint', 'complaint.view');
manager.addDocument('en', 'Please tell me the current status of my complaint', 'complaint.view');

// general.cancel
manager.addDocument('en', 'Cancel', 'general.cancel');
manager.addDocument('en', 'Exit', 'general.cancel');
manager.addDocument('en', 'Cancel the action', 'general.cancel');
manager.addDocument('en', 'Forget about it', 'general.cancel');
manager.addDocument('en', 'I don\'t want to proceed', 'general.cancel');
manager.addDocument('en', 'Stop the process', 'general.cancel');
manager.addDocument('en', 'Abort the operation', 'general.cancel');
manager.addDocument('en', 'Never mind', 'general.cancel');
manager.addDocument('en', 'I changed my mind', 'general.cancel');
manager.addDocument('en', 'Please cancel it', 'general.cancel');
manager.addDocument('en', 'Cancel this request', 'general.cancel');
manager.addDocument('en', 'Exit without submitting', 'general.cancel');
manager.addDocument('en', 'Forget this request', 'general.cancel');
manager.addDocument('en', 'Cancel the operation', 'general.cancel');
manager.addDocument('en', 'Stop everything', 'general.cancel');
manager.addDocument('en', 'Abort the task', 'general.cancel');
manager.addDocument('en', 'I no longer want to proceed', 'general.cancel');
manager.addDocument('en', 'Forget about the complaint', 'general.cancel');
manager.addDocument('en', 'Stop the process for me', 'general.cancel');
manager.addDocument('en', 'Cancel and exit', 'general.cancel');
manager.addDocument('en', 'End this now', 'general.cancel');
manager.addDocument('en', 'I want to stop this', 'general.cancel');
manager.addDocument('en', 'Don\'t proceed with the action', 'general.cancel');
manager.addDocument('en', 'Exit without confirming', 'general.cancel');
manager.addDocument('en', 'Cancel the entire process', 'general.cancel');
manager.addDocument('en', 'I want to exit', 'general.cancel');
manager.addDocument('en', 'Cancel the request I made', 'general.cancel');
manager.addDocument('en', 'I don\'t want to submit it anymore', 'general.cancel');
manager.addDocument('en', 'Forget the action I took', 'general.cancel');
manager.addDocument('en', 'Stop everything now', 'general.cancel');
manager.addDocument('en', 'Cancel this step', 'general.cancel');
manager.addDocument('en', 'Cancel my request', 'general.cancel');
manager.addDocument('en', 'Exit the process', 'general.cancel');
manager.addDocument('en', 'I want to cancel this', 'general.cancel');
manager.addDocument('en', 'I do not want to continue', 'general.cancel');
manager.addDocument('en', 'Cancel and stop', 'general.cancel');
manager.addDocument('en', 'Exit and cancel the process', 'general.cancel');
manager.addDocument('en', 'Forget everything', 'general.cancel');
manager.addDocument('en', 'End this process', 'general.cancel');
manager.addDocument('en', 'Please cancel everything', 'general.cancel');
manager.addDocument('en', 'Exit immediately', 'general.cancel');
manager.addDocument('en', 'Please stop this now', 'general.cancel');
manager.addDocument('en', 'I changed my decision', 'general.cancel');
manager.addDocument('en', 'Abort everything', 'general.cancel');
manager.addDocument('en', 'Cancel my previous action', 'general.cancel');
manager.addDocument('en', 'Don\'t proceed with this request', 'general.cancel');
manager.addDocument('en', 'End this operation', 'general.cancel');
manager.addDocument('en', 'Cancel and exit now', 'general.cancel');
manager.addDocument('en', 'Exit the current process', 'general.cancel');
manager.addDocument('en', 'Stop right now', 'general.cancel');
manager.addDocument('en', 'Cancel without submitting', 'general.cancel');

// Train and save the model
(async() => {
  await manager.train();
  manager.save();
  console.log('Model trained and saved');
})();
